/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FloraGUI.java
 *
 * Created on 28-apr-2011, 8:51:59
 */
package org.logica.cns.flora;

import jade.core.AID;
import java.awt.Color;
import org.logica.cns.flora.gui.FloraEvent;

/**
 *
 * @author eduard
 */
public class FloraGUI extends javax.swing.JFrame implements NotificationHandler {
    private AID a;

    /** Creates new form FloraGUI */
    public FloraGUI(AID a) {
        initComponents();
        jTextArea1.setBackground(Color.LIGHT_GRAY);
        jTextArea1.setSelectionColor(Color.GREEN);
        this.a = a;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocationByPlatform(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void handleNotification(FloraEvent event) {
        if (event.getState().getId().equals(a) && !event.getEventType().equals(FloraEvent.EVENTTYPE.GENERIC)) {
            int cur = jTextArea1.getDocument().getLength();
            jTextArea1.append(event.toString()+"\n");
            jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
            jTextArea1.select(cur, jTextArea1.getCaretPosition());
            toFront();
        }
    }
}
